sample_app/config/routes.rb
Rails.application.routes.draw do
  get 'todolists/new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'top' => 'homes#top'
  #URL[top]にアクセスした時に,homesコントローラーのtopアクションが呼び出される
  #そしてビューファイルの名前は、アクション名と同じにすること
  post 'todolists' => 'todolists#create'

  get 'todolists' => 'todolists#index'

  get 'todolists/:id' => 'todolists#show', as: 'todolist'
  #【重要】todolists#showの設定を、todolistとして利用できるという意味
  # .../todolists/1 や .../todolists/3 に該当する
  #非常に便利、一個一個指定はしなくていい
  get 'todolists/:id/edit' => 'todolists#edit', as: 'edit_todolist'
  #このasについては必ず確認する
  patch 'todolists/:id' => 'todolists#update', as: 'update_todolist'

end

sample_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

sample_app/app/models/list.rb
class List < ApplicationRecord
end

sample_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

sample_app/app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top

  end
end

sample_app/app/controllers/todolists_controller.rb
class TodolistsController < ApplicationController
  def new
    #viewへ渡すためのインスタンス変数にからのモデルオブジェクトを生成する
    #@listに深い意味はない。インスタンス変数の名前。
    @list = List.new
  end

  def create
    # このlistって何→新規登録するためのインスタンス（引数:list_params)
    # 急に出てきた引数もよく分からない:newに引数？？
    list = List.new(list_params)

    list.save

    redirect_to todolist_path(list.id)
    # 詳細画面へリダイレクト
    # 投稿後すぐに何を書いたかブログのように見せるため
  end

  def index
    # 全てのデータをこのインスタンス変数に入れる。意味合いを考えて複数形に。
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    #findメソッドを使って、データベースから取得し、@listへ格納する。
  end

  def edit
    @list = List.find(params[:id])
    #showと同じことを行う
  end

  def update
    list = List.find(params[:id])
    list.update(list_params)
    redirect_to todolist_path(list.id)
    
  end

  private

  def list_params
    # paramsはデータを受け取る、requireで「どこの」permitでキーを指定（何を取るか）
    params.require(:list).permit(:title, :body)

  end
end

sample_app/app/helpers/application_helper.rb
module ApplicationHelper
end

sample_app/app/helpers/homes_helper.rb
module HomesHelper
end

sample_app/app/helpers/todolists_helper.rb
module TodolistsHelper
end

sample_app/app/views/homes/top.html.erb
<h1>ここはTopページです</h1>

sample_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SampleApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

sample_app/app/views/todolists/edit.html.erb
<h1>編集画面</h1>
<%= form_for(@list, url:"/todolists/#{@list.id}") do |f| %>
    <h4>タイトル</h4>
    <%= f.text_field :title %>
    <h4>本文</h4>
    <%= f.text_area :body %>
    <%= f.submit '保存' %>
<% end %>

<!-- editで保存を何故することができるのかではなく、editで保存が押されるとこういう動作をするという考え方 -->

sample_app/app/views/todolists/index.html.erb
 <h1>投稿一覧</h1>
   <% @lists.each do |list| %>
   <!-- 見えなくていいから%に=はつかない -->
   <!-- eachとすることで、リストレコードの数だけ出力を繰り返してくれる -->
      <p>タイトル</p>
      <span>
        <%=link_to list.title, todolist_path(list.id) %>
        <!-- todolist_pathとは？ 多分ヘルパー。。。-->
      </span>
      <!-- 詳細ページへいくリンクを作成 -->
   <% end %>

sample_app/app/views/todolists/new.html.erb
<h1>新規投稿</h1>

<!-- todolistsから来るってこと -->
<!-- fも特にここでは何かもともと意味があるわけではない -->
<%= form_for(@list, url: '/todolists')do |f| %>

  <h4>タイトル</h4>
  <!-- テーブルのカラムのデータを出力 -->
  <%= f.text_field :title %>

  <h4>本文</h4>
  <%= f.text_area :body %>

  <%= f.submit '投稿' %>

<% end %>

sample_app/app/views/todolists/show.html.erb
<h2>タイトル</h2>
  <p><%= @list.title %></p>
  <!-- 何を入れるかというとタイトルとボディですよという文 -->
  <h2>本文</h2>
  <p><%= @list.body %></p>

  <%= link_to "編集", edit_todolist_path(@list.id) %> 